OUTPUTFILE: TESTS/diskviz.img
SEED: 42
BLOCKSIZE: 16384
HEADERBLOCKS: 2
ZEROPADBLOCKS: 0
RANDOMPADBLOCKS: 0
RANDOMBLOCKS: 50
ZEROBLOCKS: 50
FILLHOLESPRIMARY: RANDOM
FILLHOLESSECONDARY: ZERO

FILE: TESTS/cat.gif
FRAGMENTED: true

FILE: TESTS/earth.gif
FRAGMENTED: true

FILE: TESTS/cosmos.gif
FRAGMENTED: true

FILE: TESTS/golden-smile.gif
FRAGMENTED: true

FILE: TESTS/cyber-lsu.png
FRAGMENTED: true

FILE: TESTS/g3pres.png
FRAGMENTED: true

FILE: TESTS/KofButter.jpg
FRAGMENTED: true

FILE: TESTS/ggr-academic-genealogy.png
FRAGMENTED: true

FILE: TESTS/g3-bleh.jpg
FRAGMENTED: true

FILE: TESTS/g4-rocks.jpg
FRAGMENTED: true
