.TH mergeblockmap "1" "" "The scalpel3 Blockmap Merger" "The scalpel3 Blockmap Merger"

.SH NAME
mergeblockmap \- Merge multiple scalpel3 blockmaps into one

.SH SYNOPSIS
.B mergeblockmap
\fIoutput_file\fR
\fIimage_file\fR
\fIblockmap_file1\fR
\fIblockmap_file2\fR
[\fIblockmap_file3\fR ...]

.SH DESCRIPTION
.PP
\fBmergeblockmap\fR combines two or more scalpel3 blockmaps into a single
merged blockmap.  This is used after distributed or windowed carving
(e.g., via \fBhpcscalpel3\fR(1)) to unify the coverage information from
separate carving runs into one blockmap that reflects the combined
state.
.PP
The \fIimage_file\fR argument specifies the disk image that the blockmaps
refer to.  All input blockmaps must have been created from the same
image.

.SH SEE ALSO
.BR scalpel3 (1),
.BR crblockmap (1),
.BR modblockmap (1),
.BR cmpblockmaps (1),
.BR hpcscalpel3 (1)

.SH AUTHOR
Golden G. Richard III.
