.TH scalpel3-ctl "1" "" "The scalpel3 Controller" "The scalpel3 Controller"

.SH NAME
scalpel3-ctl \- Control and monitor a running scalpel3 instance

.SH SYNOPSIS
.B scalpel3-ctl
[\fB-b\fR]
[\fB-bv\fR \fIUUID1\fR \fIUUID2\fR]
[\fB-c\fR]
[\fB-h\fR]
[\fB-k\fR \fIUUID\fR]
[\fB-kq\fR]
[\fB-o\fR \fIscalpel_output_dir\fR]
[\fB-p\fR]
[\fB-s\fR]
[\fB-x\fR]

.SH DESCRIPTION
.PP
\fBscalpel3-ctl\fR interacts with a running \fBscalpel3\fR instance on the local machine via Unix domain sockets. It provides a "human in the loop" interface that supports initiating checkpoints, getting progress reports, terminating specific carving jobs, and graceful shutdowns.
.PP
Exactly one command option (excluding \fB-o\fR) must be specified per invocation.

.SH OPTIONS
.PP
The following options are available:

.TP
.B -b
Retrieve and display a copy of the current primary blockmap.

.TP
.BI -bv " UUID1 UUID2"
Retrieve and display contents of the blockvector associated with the job identified by primary \fIUUID1\fR and clone \fIUUID2\fR. Both UUIDs must be specified.
.br

\fBNote:\fR This option is currently not implemented in the backend and will return an error.

.TP
.B -c
Request that scalpel3 create a progress checkpoint, which updates the INPROGRESS directories, where
UUIDs of files associated with reassembly jobs can be scrutinized.  These UUIDs can be used to
interact directly with specific carving operations, using other options such as \fB-k\fR.


.TP
.B -h
Say HELLO to the scalpel3 instance. Useful for verifying IPC connectivity.

.TP
.BI -k " UUID"
Kill a specific carving job, either active or queued, using its \fIUUID\fR. Use \fB-p\fR or \fB-c\fR to obtain UUIDs of candidates currently being considered.

.TP
.B -kq
List all UUIDs currently in the kill queue.

.TP
.BI -o " scalpel_output_dir"
Specify the output directory of the targeted scalpel3 instance. This is required if the target instance is not using the default "scalpel-output" directory, as the IPC endpoint (\fI.scalpel3IPC\fR) is stored there.

.TP
.B -p
List UUIDs, file types, and current lengths for all carving candidates that are either actively being reassembled or queued for reassembly.

.TP
.B -s
Display current carving statistics.

.TP
.B -x
Request that scalpel3 checkpoint and then exit as soon as possible.

.SH SEE ALSO
.BR scalpel3 (1)

.SH AUTHOR
Golden G. Richard III.
