#!/bin/bash
#
# Build script for Scalpel3 on macOS and Linux.
#
# Library dependencies are listed in configure.ac.  On Macs, they can be
# installed using brew or macports. On Linux, just uncomment this line:
#
# sudo apt-get install gettext MORE MORE MORE
#
#
#
CURDIR=`pwd`
AUTOPATH=$CURDIR/autoconf-2.69
BINU=$CURDIR/src/binutils-2.37
OLDPATH=$PATH
export AUTOM4TE=$AUTOPATH/bin/autom4te
export AUTOM4TE_CFG=$AUTOPATH/lib/autom4te.cfg
export PERL5LIB=$AUTOPATH/lib
cd $AUTOPATH && \
./configure --srcdir=$AUTOPATH && \
make && \
export PATH=$AUTOPATH/bin:$PATH && \
cd $BINU && \
find . -type f -name 'config.cache' -print -delete && \
#aclocal && \
autoconf && \
automake --add-missing && \
./configure --prefix=`pwd`/binutils-build --enable-targets=all --disable-nls && \
make clean &&    
make && \
cd $CURDIR && \
aclocal && \
autoconf && \
automake --add-missing && \
./configure && \
make clean && \
make
export PATH=$OLDPATH

